package models.enums;

public enum EventType {
	CODE_ENTERED,
	PARTICIPATION_REQUESTED,
	NO_PARTICIPATION,
	PARTICIPATION_REJECTED,
	PARTICIPATION_APPROVED,
	
	PARTICIPANT_SEARCH_STARTED,
	PARTICIPANT_SEARCH_CLOSED,
	CODES_GENERATED,
	STUDY_STARTED
}
