package models.enums;

public enum EventType {
	CODE_ENTERED,
	PARTICIPATION_REQUESTED,
	NO_PARTICIPATION,
	PARTICIPATION_REJECTED,
	PARTICIPATION_APPROVED,
	GROUP_ASSIGNED,
	
	VALIDATION_REQUESTED,
	STUDY_VALIDATED,
	STUDY_REJECTED,
	PARTICIPANT_SEARCH_STARTED,
	PARTICIPANT_SEARCH_CLOSED,
	CODES_GENERATED,
	STUDY_STARTED,
	REQUIRED_INFORMATION_CHANGED,
	STUDY_SETUP_CHANGED
}
